### ISSUE TITLE
[ISSUE] Non-recurring completed chore switches to overdue at midnight

### ISSUE THREAD

**Issue by lymanbuttler** [ad-ha/kidschores-ha#156]
### Home Assistant Version

2025.3.4

### KidsChore Integration Version

0.3.0

### Installation Method

HACS

### Did you check for existing issues?

- [x] Yes, I have checked for existing issues
- [ ] No, I have not checked for existing issues

### Did you enable debug logging before and are ready to post logs?

- [x] Yes, I have enabled debug logging
- [ ] No, I have not enabled debug logging

### Describe the Issue

Steps to recreate:

1. Create a chore with no due date and no recurrence.
2. Use the Set/Reset Chore Due Date action/service with a templated time to give the chore a due date and time today. I use now() + timedelta(minutes=1)).isoformat() when I want something done now, with an offset of 1 minute into the future to avoid the "no due dates in the past" error.
3. Complete and approve the chore.
4. Wait until midnight.
5. The chore should now appear as overdue.

Expected behavior: once completed, the chore should not appear as Overdue again unless a due date is assigned manually or by the Set/Reset Chore Due Date action

### Logs

```yaml

```

**Comment by lymanbuttler** [comment]
Sure, here's the automation action I use:

```
action: kidschores.set_chore_due_date
data:
  chore_name: Dishes
  due_date: "{{ (now() + timedelta(minutes=1)).isoformat() }}"
```

Here's the chore data from the config file as it is without changes, when I submitted the bug report:

```
      "83075734-5b08-4489-8a84-68b9a799ad13": {
        "name": "Dishes",
        "state": "pending",
        "default_points": 1.0,
        "allow_multiple_claims_per_day": false,
        "partial_allowed": false,
        "description": "",
        "chore_labels": [],
        "icon": "mdi:silverware-clean",
        "shared_chore": false,
        "assigned_kids": [
          "869072cf-724f-43e7-810b-266c57a3d5cf"
        ],
        "recurring_frequency": "none",
        "custom_interval": null,
        "custom_interval_unit": null,
        "due_date": null,
        "last_completed": "2025-04-03T12:26:04.250646+00:00",
        "last_claimed": "2025-04-04T12:06:53.108806+00:00",
        "applicable_days": [],
        "notify_on_claim": true,
        "notify_on_approval": false,
        "notify_on_disapproval": true,
        "internal_id": "83075734-5b08-4489-8a84-68b9a799ad13"
      },
```

I deleted the chore and recreated it from scratch. Then it looked like this:

```
      "c1596925-5551-408b-98d4-1d24c66c369d": {
        "name": "Dishes",
        "state": "pending",
        "default_points": 1.0,
        "allow_multiple_claims_per_day": false,
        "partial_allowed": false,
        "description": "",
        "chore_labels": [],
        "icon": "mdi:silverware-clean",
        "shared_chore": false,
        "assigned_kids": [
          "869072cf-724f-43e7-810b-266c57a3d5cf"
        ],
        "recurring_frequency": "none",
        "custom_interval": null,
        "custom_interval_unit": null,
        "due_date": null,
        "last_completed": null,
        "last_claimed": null,
        "applicable_days": [],
        "notify_on_claim": true,
        "notify_on_approval": false,
        "notify_on_disapproval": true,
        "internal_id": "c1596925-5551-408b-98d4-1d24c66c369d"
      }
```

After using the integration to update the due date/time (NOT the service call):

```
      "c1596925-5551-408b-98d4-1d24c66c369d": {
        "name": "Dishes",
        "state": "pending",
        "default_points": 1.0,
        "allow_multiple_claims_per_day": false,
        "partial_allowed": false,
        "description": "",
        "chore_labels": [],
        "icon": "mdi:silverware-clean",
        "shared_chore": false,
        "assigned_kids": [
          "869072cf-724f-43e7-810b-266c57a3d5cf"
        ],
        "recurring_frequency": "none",
        "custom_interval": null,
        "custom_interval_unit": null,
        "due_date": "2025-04-04T14:10:00+00:00",
        "last_completed": null,
        "last_claimed": null,
        "applicable_days": [],
        "notify_on_claim": true,
        "notify_on_approval": false,
        "notify_on_disapproval": true,
        "internal_id": "c1596925-5551-408b-98d4-1d24c66c369d"
      }
```

And finally, using the service call with a templated time to update the due date/time:

```
      "c1596925-5551-408b-98d4-1d24c66c369d": {
        "name": "Dishes",
        "state": "pending",
        "default_points": 1.0,
        "allow_multiple_claims_per_day": false,
        "partial_allowed": false,
        "description": "",
        "chore_labels": [],
        "icon": "mdi:silverware-clean",
        "shared_chore": false,
        "assigned_kids": [
          "869072cf-724f-43e7-810b-266c57a3d5cf"
        ],
        "recurring_frequency": "none",
        "custom_interval": null,
        "custom_interval_unit": null,
        "due_date": "2025-04-04T14:07:34.572073+00:00",
        "last_completed": null,
        "last_claimed": null,
        "applicable_days": [],
        "notify_on_claim": true,
        "notify_on_approval": false,
        "notify_on_disapproval": true,
        "internal_id": "c1596925-5551-408b-98d4-1d24c66c369d"
      }
```

**Comment by ccpk1** [comment]
@lymanbuttler - Did you upgrade your integration to 0.3.1 yet?  I'm pretty sure these issues were resolved in that upgrade because I know I was experiencing the same prior to that release.

For reference - https://github.com/ad-ha/kidschores-ha/issues/132

**Comment by lymanbuttler** [comment]
@ccpk1 Hadn't yet as it didn't appear as an update in HACS, but I just manually installed it and will let you know if this fixes it. Many thanks to you and @ad-ha for this project!

**Comment by lymanbuttler** [comment]
Tried again after removing the integration, re-downloading 3.1.0 (which appears as 3.1.0 in HACS, but the manifest.json file still says 3.0.0) and re-creating all chores, and the problem is still there.

**Comment by ccpk1** [comment]
Hi all,

I am closing this issue as it has been resolved in the latest release: **[[v0.5.0b3](https://github.com/ad-ha/kidschores-ha/releases/tag/0.5.0b3)](https://github.com/ad-ha/kidschores-ha/releases/tag/0.5.0b3)**.

**⚠️ Important Recommendation:**
If you have not yet updated to Home Assistant 2026.2, I highly recommend **updating to this Beta version first**. Getting the integration compliant *before* the Home Assistant update is the safest way to avoid migration issues.

**If you have already updated to HA 2026.2:**
Please be aware that the new strict entity naming rules may cause the integration to look "broken" (missing entities) initially.

* **Don't panic:** Your data is safe.
* **The Fix:** Please read the latest release which includes steps to get back up and running.

**Still having trouble?**

* 📚 **Documentation:** Please review the **[[Wiki](https://github.com/ad-ha/kidschores-ha/wiki)](https://github.com/ad-ha/kidschores-ha/wiki)** for the latest troubleshooting and setup guides.
* 🐛 **New Issues:** If you still experience this specific problem *after* upgrading and following the steps above, **please open a new issue** with updated logs/diagnostics. (Please do not reply to this closed thread, as it may be missed).

Thanks for your patience!
